### ISSUE TITLE
Re-starting automated solution of Tower of Hanoi puzzle fails

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#147]
This problem affects the first version of the TowerOfHanoi.py program first introduced by PR #146.  To reproduce this bug:

1. Set up a New puzzle with 2 (or more) disks
2. Select Solve and wait until at least one disk is moved to another spindle.
3. Select Stop to stop the animation of the solution.
4. Drag the disks moved back to the leftmost spindle.
5. Select Solve to redo the automated solution.

This produces a stack trace:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/VisualizationApp.py", line 320, in animatedOperation
    command()
  File "TowerOfHanoi.py", line 531, in clickSolve
    self.solve(self.nDisks())
  File "TowerOfHanoi.py", line 442, in solve
    self.moveItemsTo(labelItems, toCoords, sleepTime=moveWait)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/VisualizationApp.py", line 610, in moveItemsTo
    self.canvas.move(item, *moveBy[i])
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 2591, in move
    self.tk.call((self._w, 'move') + args)
_tkinter.TclError: wrong # args: should be ".!canvas move tagOrId xAmount yAmount"
```

**Comment by JMCanning78** [comment]
This issue should be solved by PR #146.
