### ISSUE TITLE
Quicksort failing on some sorts

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#296]
On multiple attempts, the AdvancedSorting visualization has failed while running quicksort.  

Procedure:

1. Extend visualization window wide
2. Enter 77 and Select New to make a 77-cell table
3. Select Random Fill
4. Uncheck Use median of 3
5. Set Animation speed to max
6. Select Quicksort

Here is a stack trace of the error.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/VisualizationApp.py", line 487, in animatedOperation
    command()
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 760, in <lambda>
    "Quicksort", lambda: self.clickQuicksort(), maxRows=maxRows,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 798, in clickQuicksort
    self.quicksort(code=self.quicksortCode if self.useMedianOf3.get() else
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 315, in quicksort
    self.quicksort(lo, hipart - 1, short, code,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 315, in quicksort
    self.quicksort(lo, hipart - 1, short, code,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 315, in quicksort
    self.quicksort(lo, hipart - 1, short, code,
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 272, in quicksort
    self.insertionSort(lo, hi)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/AdvancedSorting.py", line 467, in insertionSort
    self.assignFromTemp(inner, tempVal, None)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/SortingBase.py", line 145, in assignFromTemp
    self.moveItemsOnCurve(
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/Visualization.py", line 515, in moveItemsOnCurve
    for step, _ in self.moveItemsOnCurveSequence(
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/Visualization.py", line 525, in moveItemsOnCurveSequence
    items, toPositions = self.reconcileItemPositions(items, toPositions)
  File "/Users/canning/Documents/textbooks/data_structures/Python/datastructures-visualization/PythonVisualizations/Visualization.py", line 722, in reconcileItemPositions
    raise ValueError(
ValueError: Number of items must match length of positions
```

It looks like it fails on a tiny range of cells being passed to the insertionSort:
<img width="425" alt="Screen Shot 2022-06-05 at 9 15 38 PM" src="https://user-images.githubusercontent.com/26984827/172093821-a9551f9d-6b56-4364-bd67-75386804604a.png">

**Comment by JMCanning78** [comment]
It appears to be due to the disappearance of item key values when the array cells are made too narrow.  Copying an array item to and from the temporary variable should copy only the colored rectangle, but it was expecting a text item, too.
